#!/usr/bin/env Rscript
# =============================================================================
# Render the validation sprint's result tables (markdown) from the committed CSVs,
# so every number in the write-up comes from a script output.
#   Rscript backtest/v2/report.R reports/2026-09-30/validation-sprint
# Writes <dir>/TABLES.md.
# =============================================================================

suppressPackageStartupMessages(library(data.table))

fmt <- function(x, d = 4) ifelse(is.na(x), "–", formatC(x, format = "f", digits = d))
pct <- function(x, d = 2) ifelse(is.na(x), "–", sprintf("%+.*f%%", d, 100 * x))
md_table <- function(dt) {
  h <- paste0("| ", paste(names(dt), collapse = " | "), " |")
  s <- paste0("|", paste(rep("---", ncol(dt)), collapse = "|"), "|")
  b <- apply(dt, 1, function(r) paste0("| ", paste(r, collapse = " | "), " |"))
  c(h, s, b)
}

bt2_render_tables <- function(dir) {
  out <- c("# Validation sprint v2: result tables (generated by backtest/v2/report.R)", "",
           "Tune window 2018–2022 only. Every table below is rendered from the CSVs in this directory.", "")

  f <- fread(file.path(dir, "screen", "features.csv"))
  j <- fread(file.path(dir, "screen", "joint.csv"))
  for (fam in c("ml", "ats", "tot")) {
    lab <- c(ml = "Moneyline: home win beyond the no-vig close (logistic, offset = logit close)",
             ats = "Against the spread: home margin − spread_line (OLS)",
             tot = "Totals: total points − total_line (OLS)")[[fam]]
    x <- f[family == fam][order(q_bh, p_test)]
    x <- x[, .(feature, group, n, estimate = fmt(estimate), `95% CI (week-clustered)` = paste0("[", fmt(ci_lo), ", ", fmt(ci_hi), "]"),
               `effect per SD` = fmt(effect_per_sd, 3), `MDE per SD (80% power)` = fmt(2.8 * se_robust * sd_x, 3),
               p = fmt(p_test), `p robust` = fmt(p_robust), q_BH = fmt(q_bh, 3), verdict)]
    out <- c(out, paste0("## Screen: ", lab), "", md_table(x), "")
  }
  jj <- j[, .(family, set, n, k, test, statistic = fmt(stat, 3), df, p = fmt(p_test), `robust Wald p` = fmt(p_wald_robust),
              aliased)]
  out <- c(out, "## Screen: joint tests of each feature set", "", md_table(jj), "",
           "The model-based LR/F tests are the primary joint tests. The week-clustered Wald test is shown for completeness: with 29–34 coefficients and about 90 week clusters its covariance estimate is unstable and it over-rejects (Cameron & Miller 2015), so it is not evidence on its own.", "")

  mp <- file.path(dir, "models", "scores_tune.csv")
  if (file.exists(mp)) {
    m <- fread(mp)[order(-skill)]
    mm <- m[, .(candidate, calibration, n, brier = fmt(brier), logloss = fmt(logloss), ece = fmt(ece),
                `slope [95% CI]` = paste0(fmt(slope, 2), " [", fmt(slope_lo, 2), ", ", fmt(slope_hi, 2), "]"),
                `skill vs close [95% CI]` = paste0(pct(skill), " [", pct(skill_lo), ", ", pct(skill_hi), "]"),
                `DM p (BH)` = fmt(dm_p_bh, 3))]
    out <- c(out, "## Blends and calibration maps (moneyline, Tune out-of-fold)", "", md_table(mm), "")
  }
  cp <- file.path(dir, "models", "control_shuffled_labels.csv")
  if (file.exists(cp)) {
    k <- fread(cp)
    kk <- k[, .(model, n, `skill vs climatology [95% CI]` = paste0(pct(skill_vs_climatology), " [", pct(skill_lo), ", ", pct(skill_hi), "]"),
                passed)]
    out <- c(out, "## Control: shuffled labels (outcomes permuted globally; skill must not exceed climatology)", "", md_table(kk), "")
  }
  hp <- file.path(dir, "handicap", "scores_tune.csv")
  if (file.exists(hp)) {
    h <- fread(hp)
    hh <- h[, .(market, candidate, n, brier = fmt(brier), `skill vs devigged close [95% CI]` = paste0(pct(skill), " [", pct(skill_lo), ", ", pct(skill_hi), "]"),
                `DM p (BH)` = fmt(dm_p_bh, 3))]
    out <- c(out, "## Handicapping: spread and totals (Tune out-of-fold)", "", md_table(hh), "")
    b <- fread(file.path(dir, "handicap", "betting_tune.csv"))
    bb <- b[, .(market, candidate, picks, hits, `hit rate [95% Wilson]` = paste0(fmt(hit_rate, 3), " [", fmt(hit_lo, 3), ", ", fmt(hit_hi, 3), "]"),
                `break-even` = fmt(breakeven, 3), ROI = pct(roi, 1), `p (hit > break-even)` = fmt(p_binom_vs_breakeven, 3))]
    out <- c(out, "## Handicapping: flat 1-unit bets at the closing price when the model is ≥ 3 points off the market", "", md_table(bb), "")
  }
  writeLines(out, file.path(dir, "TABLES.md"), useBytes = TRUE)
  invisible(file.path(dir, "TABLES.md"))
}

if (sys.nframe() == 0L) {
  a <- commandArgs(trailingOnly = TRUE)
  if (!length(a)) stop("usage: Rscript backtest/v2/report.R <sprint dir>")
  p <- bt2_render_tables(a[1])
  # LF on every OS (audit T6)
  txt <- readLines(p, warn = FALSE)
  con <- file(p, open = "wb"); writeBin(charToRaw(enc2utf8(paste0(paste(txt, collapse = "\n"), "\n"))), con); close(con)
  cat("wrote", p, "\n")
}
