#!/usr/bin/env Rscript
# =============================================================================
# Render the blend research tables (markdown) from the CSVs that
# backtest/v3/sprint.R wrote, so every number in the write-up comes from a
# script output.
#   Rscript backtest/v3/report.R reports/2026-10-01/blend-research
# Writes <dir>/TABLES.md (LF line endings).
# =============================================================================

suppressPackageStartupMessages(library(data.table))

BT3_V2_DIR_REPORT <- file.path("reports", "2026-09-30", "validation-sprint")
fmt <- function(x, d = 4) ifelse(is.na(x), "–", formatC(x, format = "f", digits = d))
pct <- function(x, d = 2) ifelse(is.na(x), "–", sprintf("%+.*f%%", d, 100 * x))
ci <- function(est, lo, hi, f = fmt, ...) paste0(f(est, ...), " [", f(lo, ...), ", ", f(hi, ...), "]")
md_table <- function(dt) {
  dt <- as.data.frame(dt)
  h <- paste0("| ", paste(names(dt), collapse = " | "), " |")
  s <- paste0("|", paste(rep("---", ncol(dt)), collapse = "|"), "|")
  b <- apply(dt, 1, function(r) paste0("| ", paste(r, collapse = " | "), " |"))
  c(h, s, b)
}
rd <- function(dir, ...) {
  p <- file.path(dir, ...)
  if (file.exists(p)) fread(p) else NULL
}
by_week_wide <- function(x) {
  w <- dcast(x, wk + n_train ~ term, value.var = "value")
  w[, season := wk %/% 100L]
  w
}

bt3_render_tables <- function(dir) {
  sc <- rd(dir, "scores", "scores_tune.csv")
  comp <- rd(dir, "compute", "seconds.csv")
  meta <- jsonlite::read_json(file.path(dir, "run_meta.json"), simplifyVector = TRUE)
  out <- c("# Blend research v3: result tables (generated by backtest/v3/report.R)", "",
           sprintf("Tune window 2018–2022 only: %d non-tie games, scored against the no-vig close (C0). Every table below is rendered from the CSVs in this directory. BH q-values run across all %d moneyline candidates (v2 and v3). Bootstrap: week blocks, B = 10,000.",
                   meta$n_tune_scored, meta$n_candidates_bh), "")

  # 1. headline: one row per family, uncalibrated
  fit <- comp[stage %in% c("level0 (v2 code)", "v3 new"), .(family, fit_seconds)]
  h <- merge(sc[calibration == "none"], fit, by = "family", all.x = TRUE)[order(-skill)]
  hh <- h[, .(family, source, `what it is` = description, Brier = fmt(brier),
              `Brier skill vs close [95% CI]` = paste0(pct(skill), " [", pct(skill_lo), ", ", pct(skill_hi), "]"),
              `log-loss skill [95% CI]` = paste0(pct(ll_skill), " [", pct(ll_skill_lo), ", ", pct(ll_skill_hi), "]"),
              `DM p` = fmt(dm_p, 3), `BH q` = fmt(bh_q, 3),
              `slope [95% CI]` = ci(slope, slope_lo, slope_hi, d = 2),
              `intercept [95% CI]` = ci(recal_intercept, recal_intercept_lo, recal_intercept_hi, d = 3),
              ECE = fmt(ece), `fit (s)` = ifelse(is.na(fit_seconds), "–", formatC(fit_seconds, format = "f", digits = 0)))]
  out <- c(out, "## 1. Every family, uncalibrated (headline)", "",
           "Slope and intercept come from the logistic recalibration fit y ~ a + b·logit(p) (perfect calibration: a = 0, b = 1). DM p is the one-sided Diebold–Mariano (HLN) test that the candidate's Brier is lower than the close's. `fit (s)` sums the weekly fit times over the whole walk (v2 families: their level-0 walk 2014–2022 in this run; the base models C1, C2, E1 are not timed separately). The table is sorted by skill.", "",
           md_table(hh), "")

  # 2. every candidate incl. v2 calibration variants
  a <- sc[order(-skill)]
  aa <- a[, .(candidate, calibration, source, n, Brier = fmt(brier), `log loss` = fmt(logloss),
              `Brier skill [95% CI]` = paste0(pct(skill), " [", pct(skill_lo), ", ", pct(skill_hi), "]"),
              `log-loss skill [95% CI]` = paste0(pct(ll_skill), " [", pct(ll_skill_lo), ", ", pct(ll_skill_hi), "]"),
              `DM p (Brier)` = fmt(dm_p, 3), `BH q` = fmt(bh_q, 3), `DM p (log loss)` = fmt(dm_ll_p, 3))]
  out <- c(out, "## 2. Every candidate, including v2's calibration variants", "", md_table(aa), "")

  # 3. probability quality
  q <- a[, .(candidate, calibration, ECE = fmt(ece),
             `recalibration intercept a [95% CI]` = ci(recal_intercept, recal_intercept_lo, recal_intercept_hi, d = 3),
             `recalibration slope b [95% CI]` = ci(slope, slope_lo, slope_hi, d = 3),
             `calibration-in-the-large [95% CI]` = ci(citl, citl_lo, citl_hi, d = 3),
             `mean abs logit gap vs close` = fmt(mean_abs_logit_vs_close, 3))]
  out <- c(out, "## 3. Probability quality: calibration of every candidate", "",
           "ECE uses 10 equal-count bins. Calibration-in-the-large is the intercept of y ~ 1 with offset logit(p) (0 = right on average). All CIs are Wald 95%. The gap column is the mean |logit(p) − logit(close)|: how far the candidate moves from the market.", "",
           md_table(q), "")

  # 4. reliability (compact): uncalibrated columns
  rel <- rd(dir, "scores", "reliability_tune.csv")
  ru <- rel[calibration == "none"]
  ru[, cell := paste0(formatC(mean_p, format = "f", digits = 3), " / ", formatC(obs_rate, format = "f", digits = 3))]
  rw <- dcast(ru, candidate ~ bin, value.var = "cell")
  setnames(rw, setdiff(names(rw), "candidate"), paste0("bin ", setdiff(names(rw), "candidate")))
  rw <- rw[order(match(candidate, h$candidate))]
  nb <- range(ru$n)
  out <- c(out, "## 4. Reliability: mean predicted / observed home-win rate in 10 equal-count bins", "",
           sprintf("Bins are deciles of each candidate's own predictions (n = %d–%d games per bin). `reliability_tune.csv` has every candidate, including v2's calibration variants, with each bin's n and a Wilson 95%% CI on the observed rate.", nb[1], nb[2]), "",
           md_table(rw), "")
  # full reliability of the close and the new families, with n and Wilson CIs
  rn <- rel[calibration == "none" & candidate %in% c("C0", sc[source == "v3 (new)", candidate])]
  rn <- rn[order(match(candidate, h$candidate), bin)]
  rr <- rn[, .(candidate, bin, n, `mean predicted` = fmt(mean_p, 3),
               `observed [Wilson 95% CI]` = ci(obs_rate, obs_lo, obs_hi, d = 3))]
  out <- c(out, "### Reliability of the close and the new families, with n and CIs", "", md_table(rr), "")

  # 5. by season
  bs <- rd(dir, "scores", "skill_by_season.csv")
  bw <- dcast(bs, candidate ~ season, value.var = "skill")
  for (s in setdiff(names(bw), "candidate")) set(bw, j = s, value = pct(bw[[s]]))
  ns <- unique(bs[, .(season, n)])
  setnames(bw, setdiff(names(bw), "candidate"), paste0(ns$season, " (n ", ns$n, ")"))
  bw <- bw[order(match(candidate, h$candidate))]
  out <- c(out, "## 5. Brier skill vs the close by season (uncalibrated, no CIs)", "", md_table(bw), "")

  # 6. controls
  ctl <- rd(dir, "controls", "shuffled_labels.csv")
  if (!is.null(ctl)) {
    cc <- ctl[, .(model, `refit as` = family_type, n,
                  `skill vs climatology [95% CI]` = paste0(pct(skill_vs_climatology), " [", pct(skill_lo), ", ", pct(skill_hi), "]"),
                  `passed (CI lower bound <= 0)` = passed, `point estimate <= 0` = point_not_positive)]
    out <- c(out, "## 6. Control: shuffled labels", "",
             "Outcomes permuted globally with v2's seed (the same permutation as v2's control); every learner, including the four level-0 families that feed the meshes, refit walk-forward on the permuted labels; scored on Tune against an expanding home-win-rate climatology.", "",
             md_table(cc), "")
  }

  # 7. meshes
  out <- c(out, "## 7. Mesh diagnostics", "")
  for (m in c("s1", "s1_min")) {
    x <- rd(dir, "meshes", paste0(m, "_by_week.csv"))
    if (is.null(x)) next
    w <- by_week_wide(x)
    lv <- setdiff(names(w), c("wk", "n_train", "season", "(Intercept)", "lambda"))
    s <- w[, c(list(weeks = .N, `mean intercept` = fmt(mean(`(Intercept)`), 4),
                    `largest abs level-0 weight` = formatC(max(abs(as.matrix(.SD))), format = "g", digits = 3),
                    `mean lambda` = fmt(mean(lambda), 3))), by = season, .SDcols = lv]
    out <- c(out, sprintf("### %s: meta-learner weights by Tune season (ridge on %s)", toupper(m), paste(lv, collapse = ", ")), "",
             md_table(s), "")
  }
  r1 <- rd(dir, "meshes", "r1_by_week.csv")
  if (!is.null(r1)) {
    s <- r1[, .(weeks = .N, `median rounds` = as.numeric(stats::median(value)), min = min(value), max = max(value)), by = .(season = wk %/% 100L)]
    out <- c(out, "### R1: boosting rounds chosen by season-grouped CV", "", md_table(s), "")
  }
  g <- rd(dir, "meshes", "o1_eta_grid.csv")
  if (!is.null(g)) {
    out <- c(out, "### O1: learning-rate selection on 2014–2017 (before Tune)", "",
             md_table(g[, .(eta, n, `Brier 2014-2017` = fmt(brier, 5), chosen)]), "")
    o <- rd(dir, "meshes", "o1_by_week.csv")
    last <- o[, .SD[wk == max(wk)], by = .(season = wk %/% 100L)][season >= 2017L]
    lw <- dcast(last, season ~ expert, value.var = "weight")
    for (e in setdiff(names(lw), "season")) set(lw, j = e, value = fmt(lw[[e]], 3))
    out <- c(out, "### O1: expert weights in the last week of each season", "", md_table(lw), "")
  }
  gc <- rd(dir, "meshes", "level0_gap_correlation_tune.csv")
  if (!is.null(gc)) {
    for (j in setdiff(names(gc), "column")) set(gc, j = j, value = fmt(gc[[j]], 2))
    out <- c(out, "### Level 0: correlation of each model's logit gap to the close (Tune games)", "", md_table(gc), "")
  }

  # 8. families
  out <- c(out, "## 8. Family diagnostics", "")
  for (m in c("g2", "g2_gaps")) {
    x <- rd(dir, "families", paste0(m, "_by_week.csv"))
    if (is.null(x)) next
    s <- x[term != "intercept", .(`median edf` = fmt(as.numeric(stats::median(value)), 3), `max edf` = fmt(max(value), 3)), by = .(term, season = wk %/% 100L)]
    sw <- dcast(s, term ~ season, value.var = "median edf")
    out <- c(out, sprintf("### %s: median effective degrees of freedom of each smooth, by season (0 = shrunk away)", toupper(m)), "", md_table(sw), "")
  }
  t1 <- rd(dir, "families", "t1_by_week.csv")
  if (!is.null(t1)) {
    w <- by_week_wide(t1)
    s <- w[, .(weeks = .N, `singular fits` = sum(singular), `mean SD home team` = fmt(mean(sd_home), 3),
               `mean SD away team` = fmt(mean(sd_away), 3), `intercept range` = paste0(fmt(min(intercept), 3), " to ", fmt(max(intercept), 3)),
               warnings = sum(warnings), `training games` = paste0(min(n_train), "–", max(n_train))), by = season]
    out <- c(out, "### T1: random-intercept SDs (logit scale) and fixed intercept by season", "", md_table(s), "")
  }
  n1 <- rd(dir, "families", "n1_tuning.csv")
  if (!is.null(n1)) {
    ch <- n1[chosen == TRUE, .(variant, season, size, decay, `CV deviance` = fmt(cv_deviance, 4))]
    grid <- n1[, .(decays = paste(sort(unique(decay)), collapse = ", ")), by = variant]
    out <- c(out, "### N1 / N1_NARROW: size and decay chosen by season-grouped CV at each season's first week", "",
             paste0("Decay grids: ", paste(sprintf("%s {%s}", grid$variant, grid$decays), collapse = "; "), ". Sizes 1–3."), "",
             md_table(ch), "")
  }

  # 9. reproduction and compute
  chk <- rd(dir, "level0", "check_vs_v2.csv")
  out <- c(out, "## 9. Level 0 reproduces v2, and compute", "",
           "Level 0 is v2's own code (`bt2_walk_models`) run again for 2014–2022. Its Tune predictions are compared with v2's committed tracking file, which v2 rounded to 8 decimals.", "",
           md_table(chk[, .(column, games, `max abs diff` = formatC(max_abs_diff, format = "e", digits = 2),
                            `after 8-decimal rounding` = formatC(max_abs_diff_rounded, format = "e", digits = 2))]), "")
  vr <- rd(dir, "v2_reproduction.csv")
  if (!is.null(vr)) out <- c(out, sprintf("A separate re-run of the v2 stages reproduced %d of %d v2 output files byte for byte (`v2_reproduction.csv`).", sum(vr$identical), nrow(vr)), "")
  dt <- rd(dir, "determinism.csv")
  if (!is.null(dt)) out <- c(out, sprintf("A second full run of `backtest/v3/sprint.R` reproduced %d of %d CSVs of this run byte for byte (`determinism.csv`; the timing files are not compared).", sum(dt$identical), nrow(dt)), "")
  cm <- comp[, .(family, stage, `fit seconds` = formatC(fit_seconds, format = "f", digits = 0),
                 `wall seconds` = ifelse(is.na(wall_seconds), "–", formatC(wall_seconds, format = "f", digits = 0)))]
  out <- c(out, sprintf("Run with %d worker processes; level-0 stage wall-clock %.0f s; whole run %.0f s. Fit seconds sum the weekly fits across workers.",
                        meta$workers, meta$level0$wall_seconds, meta$runtime_sec), "", md_table(cm), "")
  bt3_write_md(out, file.path(dir, "TABLES.md"))
}

bt3_write_md <- function(lines, p) {
  con <- file(p, open = "wb")
  on.exit(close(con))
  writeBin(charToRaw(enc2utf8(paste0(paste(lines, collapse = "\n"), "\n"))), con)
  invisible(p)
}

# ---------------------------------------------------------------------------
# REPORT.md: the write-up. Every number is read from the CSVs; each sentence
# that states a finding is guarded by a check that stops the render if the
# data say otherwise, so the prose cannot drift from the outputs.
# ---------------------------------------------------------------------------
bt3_render_report <- function(dir) {
  sc <- rd(dir, "scores", "scores_tune.csv")
  ctl <- rd(dir, "controls", "shuffled_labels.csv")
  comp <- rd(dir, "compute", "seconds.csv")
  meta <- jsonlite::read_json(file.path(dir, "run_meta.json"), simplifyVector = TRUE)
  rel <- rd(dir, "scores", "reliability_tune.csv")
  bs <- rd(dir, "scores", "skill_by_season.csv")
  s1 <- by_week_wide(rd(dir, "meshes", "s1_by_week.csv"))
  r1 <- rd(dir, "meshes", "r1_by_week.csv")
  o1g <- rd(dir, "meshes", "o1_eta_grid.csv")
  o1w <- rd(dir, "meshes", "o1_by_week.csv")
  t1 <- by_week_wide(rd(dir, "families", "t1_by_week.csv"))
  g2 <- rd(dir, "families", "g2_by_week.csv")
  n1 <- rd(dir, "families", "n1_tuning.csv")
  chk <- rd(dir, "level0", "check_vs_v2.csv")
  vr <- rd(dir, "v2_reproduction.csv")
  dt <- rd(dir, "determinism.csv")
  guard <- function(ok, what) if (!isTRUE(ok)) stop("REPORT.md not rendered: the data contradict the text (", what, ")", call. = FALSE)
  pcs <- function(x, d = 2) sprintf("%+.*f%%", d, 100 * x)
  sk <- function(r, d = 2) sprintf("%s [%s, %s]", pcs(r$skill, max(d, 3)), pcs(r$skill_lo, d), pcs(r$skill_hi, d))
  row <- function(nm) sc[candidate == nm & calibration == "none"]

  cand <- sc[column != "p_c0"]
  new <- sc[source == "v3 (new)"][order(-skill)]
  c0 <- row("C0")
  guard(nrow(cand) == meta$n_candidates_bh, "candidate count")
  guard(!any(cand$skill_lo > 0), "a candidate's skill CI lies above 0")
  min_q <- min(cand$bh_q)
  guard(min_q >= 0.05, "a BH q-value below 0.05")
  best <- new[1]
  guard(best$candidate == "S1", "S1 is the best new point estimate")
  guard(cand[which.max(skill), candidate] == "S1", "S1 is the best point estimate of all candidates")
  worse_new <- new[skill_hi < 0]
  worse_v2 <- cand[source != "v3 (new)" & skill_hi < 0]
  guard(all(worse_v2$family %in% c("C1", "C2", "E1")), "only the unanchored base models are significantly worse among v2's")
  v2ctl <- fread(file.path(BT3_V2_DIR_REPORT, "models", "control_shuffled_labels.csv"))
  m_ctl <- merge(v2ctl[, .(model, v2 = skill_vs_climatology)], ctl[, .(model, v3 = skill_vs_climatology)], by = "model")
  guard(nrow(m_ctl) == 3L && max(abs(m_ctl$v2 - m_ctl$v3) / abs(m_ctl$v2)) < 1e-5, "v2's shuffled-label control is reproduced")
  s1_lv <- setdiff(names(s1), c("wk", "n_train", "season", "(Intercept)", "lambda"))
  s1_max <- max(abs(as.matrix(s1[, ..s1_lv])))
  guard(s1_max < 1e-6, "S1 level-0 weights are zero")
  s1_int <- s1[, .(int = mean(`(Intercept)`)), by = season]
  r1s <- r1[, .(med = as.numeric(stats::median(value))), by = .(season = wk %/% 100L)][order(season)]
  eta <- meta$o1$eta
  guard(eta > min(o1g$eta) && eta < max(o1g$eta), "O1 eta is interior to its grid")
  o1_last <- o1w[wk == max(wk)]
  w_of <- function(e) o1_last[expert == e, weight]
  t1_sing <- sum(t1$singular); t1_n <- nrow(t1)
  t1_both0 <- sum(t1$sd_home < 1e-4 & t1$sd_away < 1e-4)
  t1_maxsd <- max(c(t1$sd_home, t1$sd_away))
  g2_late <- g2[term != "intercept" & wk %/% 100L >= 2019L, .(med = as.numeric(stats::median(value))), by = .(term, season = wk %/% 100L)]
  guard(max(g2_late$med) < 1, "G2's smooths are shrunk below a straight line after 2018")
  n1c <- n1[chosen == TRUE]
  guard(all(n1c[variant == "N1", decay] == max(n1[variant == "N1", decay])), "N1 chose its largest decay in every season")
  guard(all(n1c[variant == "N1_NARROW", decay] == max(n1[variant == "N1_NARROW", decay])), "N1_NARROW chose decay 100 in every season")
  guard(all(ctl$passed), "every shuffled-label control passes")
  guard(identical(ctl[model == "N1", skill_vs_climatology], ctl[model == "N1_NARROW", skill_vs_climatology]),
        "N1 and N1_NARROW are identical under permutation")
  guard(all(vr$identical), "every v2 file reproduced")
  guard(!is.null(dt) && all(dt$identical), "a second full run reproduced every CSV")
  guard(max(chk$max_abs_diff_rounded) <= 1e-12, "level 0 reproduces v2")
  by_s <- function(nm, s) bs[candidate == nm & season == s, skill]
  unc <- sc[calibration == "none" & column != "p_c0"]
  miscal <- unc[slope_lo > 1 | slope_hi < 1 | recal_intercept_lo > 0 | recal_intercept_hi < 0]
  guard(all(miscal$family %in% c("XGB_FREE", "C1", "C2", "E1")), "no anchored family is miscalibrated")
  ctl_pos <- ctl[skill_vs_climatology > 0]
  fit_of <- function(f, st = "v3 new") comp[family == f & stage == st, fit_seconds]
  width <- function(nm) { r <- row(nm); 100 * (r$skill_hi - r$skill_lo) }

  out <- c("# Blend research v3: can a mesh of XGBoost and logistic regression, or another model family, beat the close?", "",
           "<!-- rendered by backtest/v3/report.R from the CSVs in this directory; do not edit by hand -->", "",
           "**Owner's request (2026-10-01):** \"Spend more time improving model accuracy and blending. Look into XGBoost blends and meshes with logistic regression, other models.\"",
           "",
           "**Added 2026-10-03:** \"Continue with all full access and testing, probabilities.\" So every family, new and v2, now has complete probability-quality evidence: Brier and log-loss skill with CIs, the logistic recalibration slope and intercept, ECE, and a 10-bin reliability table.",
           "", "## Short answer", "",
           sprintf("- **No.** On the %s non-tie Tune games (2018–2022), no mesh and no other family beats the no-vig close.", format(meta$n_tune_scored, big.mark = ",")),
           sprintf("  - The best new point estimate is S1 at %s Brier skill.", sk(best)),
           sprintf("  - Every interval includes zero or lies below it, and after Benjamini–Hochberg across all %d moneyline candidates (v2 and v3) every q-value is %s. The smallest one-sided Diebold–Mariano p among the new candidates is %s (%s).",
                   nrow(cand), fmt(min_q, 3), fmt(min(new$dm_p), 3), new[which.min(dm_p), candidate]),
           "- **The meshes collapse onto the market.**",
           sprintf("  - S1's ridge meta-learner gives all seven level-0 models a weight of zero (largest |weight| %s) in every Tune week. So S1 is the close plus a walk-forward intercept, and that intercept is its whole edge.",
                   formatC(s1_max, format = "g", digits = 2)),
           sprintf("  - R1's cross-validated boosting rounds fall from a median of %g in %d to %g in %d: as the training window grows, the booster finds less to learn beyond the glmnet.",
                   r1s$med[1], r1s$season[1], r1s$med[nrow(r1s)], r1s$season[nrow(r1s)]),
           sprintf("  - O1 ends with its weight on the close (%.2f) and the four anchored blends (%.2f together); Elo, EPA and E1 end near zero (%.4f together).",
                   w_of("C0"), sum(sapply(c("GLMNET", "XGB", "LR_E1", "GBM"), w_of)), sum(sapply(c("C1", "C2", "E1"), w_of))),
           "- **The other families find nothing either.**",
           sprintf("  - G2's smooths are shrunk to at most %s effective degrees of freedom after 2018 (season medians; a straight line is 1). Adding the four Tune-screened features makes it worse than the gap-only GAM: G2 %s against G2_GAPS %s.",
                   fmt(max(g2_late$med), 2), pcs(row("G2")$skill, 3), pcs(row("G2_GAPS")$skill, 3)),
           sprintf("  - T1's fits are singular (a team variance estimated at zero) in %d of %d weeks, and both team variances are zero in %d. The largest team SD in any week is %s on the logit scale. No team is detectably mispriced.",
                   t1_sing, t1_n, t1_both0, fmt(t1_maxsd, 2)),
           sprintf("  - N1's cross-validation picks the largest decay in every season, which pins it to the close (mean |logit gap| %s, skill %s).",
                   fmt(row("N1")$mean_abs_logit_vs_close, 3), sk(row("N1"))),
           sprintf("  - Among the new candidates the only significant result is negative: N1_NARROW, the first version of N1, at %s.", sk(row("N1_NARROW"))),
           sprintf("- **Probabilities.** The anchored families are as well calibrated as the close. The close has recalibration slope %s and intercept %s, and ECE %s.",
                   ci(c0$slope, c0$slope_lo, c0$slope_hi, d = 2), ci(c0$recal_intercept, c0$recal_intercept_lo, c0$recal_intercept_hi, d = 3), fmt(c0$ece)),
           sprintf("  - Among the uncalibrated families, only %s %s a slope CI that excludes 1 or an intercept CI that excludes 0.",
                   if (nrow(miscal)) paste(miscal$candidate, collapse = ", ") else "none", if (nrow(miscal) == 1L) "has" else "have"),
           sprintf("- **Controls pass.** With the outcomes shuffled, no family, new or v2, shows positive skill over climatology (%d of %d pass; largest point estimate %s).",
                   sum(ctl$passed), nrow(ctl), pcs(max(ctl$skill_vs_climatology), 2)),
           "- **Nothing here is validated.** This is exploration on the window v2 already used for every choice.", "",
           "All tables: `TABLES.md`, rendered by `backtest/v3/report.R` from the CSVs in this directory.", "",
           "**Reproduce:**", "```",
           "Rscript backtest/v3/sprint.R --out reports/2026-10-01/blend-research --workers 8",
           "Rscript backtest/v3/report.R reports/2026-10-01/blend-research", "```",
           "`--workers` only sets how many local R processes share the weekly fits. Each fit sets its own seed, so the outputs do not depend on it (the chunk-invariance test). The reproduction checks are `backtest/v3/check_v2_repro.R` (v2 unchanged) and `backtest/v3/check_rerun.R` (a second v3 run).", "")

  out <- c(out, "## What this is, and what it is not", "",
           "- **Exploration on a window v2 already used.**",
           "  - Tune 2018–2022 was the window for every v2 choice.",
           "  - A good result here would be a *hypothesis* for the v2 protocol, not validation. Nothing below is \"validated\" or \"calibrated\" in the protocol's sense.",
           "- **Data:**",
           "  - Only Tune 2018–2022 is scored, with 2010–2017 as training history.",
           "  - Confirm 2023–2024 and the sealed 2025 holdout were not built or scored. The sha-locked input files hold rows up to 2024. Each table is cut at 2022 right after its sha256 check, before any feature or model sees it, and every v3 fit stops on a row after 2022 (`bt3_guard`).",
           "  - v3 checks its base models against v2's Tune-only tracking file. It never opens v1's `predictions.csv`, which also holds Confirm rows.",
           "  - No 2025 row exists in any input. v2's sealed-season guard at 2024 is unchanged.",
           "- **v2 is unchanged.** No file under `backtest/v2/`, `backtest/*.R` or `backtest/eval_windows/` was edited, and `PROTOCOL-DRAFT.md` is untouched.",
           sprintf("  - A fresh re-run of the v2 stages reproduced %d of %d v2 output files byte for byte: 10 CSVs and TABLES.md (`v2_reproduction.csv`).", sum(vr$identical), nrow(vr)),
           sprintf("  - Level 0, regenerated inside v3 with v2's code, equals v2's committed Tune predictions exactly at their 8-decimal rounding: largest difference %s (`level0/check_vs_v2.csv`).",
                   formatC(max(chk$max_abs_diff_rounded), format = "e", digits = 1)),
           "- **No new packages.** glmnet, xgboost, mgcv, lme4 and nnet all come from `renv.lock`. SVM was excluded because it does not give probabilities.", "")

  out <- c(out, "## Method", "", "### Candidates", "",
           "Every candidate is fit walk-forward by week, on games that kicked off before the week's first kickoff. Every one is built on the no-vig close: as an offset, as a base margin, or (O1) as one of the experts.", "",
           md_table(data.table(
             Label = c("**S1**", "**S1_MIN**", "**R1**", "**O1**", "**G2**", "**G2_GAPS**", "**T1**", "**N1**", "**N1_NARROW**"),
             `What it is` = c("Stacked mesh", "S1 with `lambda.min`", "Residual mesh: XGBoost on top of the logistic blend", "Online convex blend",
                              "GAM", "GAM without screen features", "Team mixed model", "Neural net", "N1 as first run"),
             Inputs = c("Logits of the 7 level-0 predictions: LR_E1, GLMNET, XGB, GBM, C1 (Elo), C2 (EPA GLM), E1 (v1 ensemble)",
                        "As S1", "v2 features: Elo and EPA gaps plus 27 situational features", "The 7 level-0 predictions plus the close",
                        "Shrinkage smooths of the Elo and EPA gaps and of the v2 moneyline screen's 4 best features (raw p < 0.10: time zones crossed, closed roof, west-coast early kickoff, linebacker injuries)",
                        "Elo and EPA gap smooths", "Home and away franchise", "logit(close) plus the v2 features", "As N1"),
             `How it is fit` = c("Ridge logistic (glmnet, alpha 0) with offset logit(close) and an unpenalised intercept; lambda.1se from season-grouped CV on the training games",
                                 "Declared sensitivity variant of the lambda rule",
                                 "xgboost with `base_margin` = the anchored glmnet's out-of-fold logit; v2 XGB hyperparameters; rounds by early stopping in season-grouped CV on the training games, then refit",
                                 sprintf("Exponentially weighted average on cumulative Brier loss; eta = %g, chosen on 2014–2017", eta),
                                 "`mgcv::gam`, REML, `bs = \"ts\"` (binary features as ridge-penalised `bs = \"re\"` terms), offset logit(close); every earlier game from 2010",
                                 "As G2. The selection-free check on G2",
                                 "`lme4::glmer` with offset logit(close) and random intercepts for the home and the away team; rolling window = current season to date plus 2 prior seasons",
                                 "`nnet`, 1 hidden layer (size 1–3) with skip connections; the skip weight on logit(close) is fixed at 1 (an offset); size and decay (1 to 10,000) by season-grouped CV at each season's first week",
                                 "Decay grid 1 to 100 only (see Disclosures)"))), "",
           "### How the nesting prevents leakage", "",
           "1. **Level 0 is v2's own code, unchanged** (`bt2_walk_models`).",
           "   - For each week from 2014 week 1, each v2 family is fit on every labelled game from 2010 that kicked off before that week, then predicts the week.",
           "   - So every level-0 prediction is out of fold and point in time.",
           "   - C1, C2 and E1 are v1's walk-forward base models.",
           "2. **Level 1 for a Tune week uses only games that kicked off before that week:**",
           "   - S1 and S1_MIN train on those games' level-0 predictions, each made before its own week, and on their outcomes. Lambda is chosen by CV inside that training set. They then predict the week from its own level-0 predictions.",
           "   - R1's base margin is the glmnet's out-of-fold prediction on every training row and on the target week, so the booster fits the residual it will actually face. Its rounds are chosen by CV inside the training set.",
           "   - O1's weights for a week depend only on the Brier losses of earlier games. eta was fixed once, on 2014–2017.",
           "   - G2, T1 and N1 train on earlier games (T1 on its rolling window). N1's size and decay are chosen at each season's first week, on games before it.",
           sprintf("3. **Burn-in.** Level 0 starts in 2014, and the meta-learners (S1, S1_MIN, R1) need at least %d level-0 games over %d seasons.",
                   meta$burn_in$meta_min_train, meta$burn_in$meta_min_seasons),
           sprintf("   - Before the first Tune week they already have 2014–2017 (%s labelled games; `meshes/s1_by_week.csv`).", format(min(s1$n_train), big.mark = ",")),
           "   - O1 starts in 2014 with equal weights.",
           "   - Burn-in weeks are not scored, and no Tune week is excluded.",
           "4. **Tests** (`tests/testthat/test-backtest-v3-meshes.R`):",
           "   - **Leak canary.** Every later outcome is flipped, including the target week's own, and every later feature, price, level-0 prediction and team label is rewritten. The target week's predictions stay bit-identical for all 9 new candidates.",
           "   - **End-to-end nesting.** Level 0 refit with v2's code on the rewritten data feeds S1 and R1, with the same result.",
           "   - Determinism run to run.",
           "   - **Chunk invariance:** walking weeks together equals walking them one at a time, which is why the parallel run equals a serial one.",
           "   - Shuffled-label sanity, and O1 weights use past losses only.",
           "   - N1 keeps its market weight at 1. An unanchored net at the same decay collapses toward 0.5.",
           "   - N1 tuning uses only games before the season, and every v3 fit refuses a 2023 row.",
           "- **Statistics (as v2):**",
           "  - Brier and log-loss skill vs the close, with week-block bootstrap 95% CIs (B = 10,000, v2's seed, so v2 rows keep their v2 intervals).",
           "  - One-sided Diebold–Mariano tests with the HLN correction.",
           "  - BH q-values across all moneyline candidates.",
           "  - Logistic recalibration y ~ a + b·logit(p) with Wald CIs, calibration-in-the-large, and ECE with reliability in 10 equal-count bins.",
           "  - v2 rows are re-scored from v2's committed per-game file, so v2 and v3 share one multiplicity family.", "")

  fit <- comp[stage %in% c("level0 (v2 code)", "v3 new"), .(family, fit_seconds)]
  h <- merge(sc[calibration == "none"], fit, by = "family", all.x = TRUE)[order(-skill)]
  hh <- h[, .(family, source, Brier = fmt(brier),
              `Brier skill vs close [95% CI]` = paste0(pct(skill), " [", pct(skill_lo), ", ", pct(skill_hi), "]"),
              `log-loss skill [95% CI]` = paste0(pct(ll_skill), " [", pct(ll_skill_lo), ", ", pct(ll_skill_hi), "]"),
              `DM p` = fmt(dm_p, 3), `BH q` = fmt(bh_q, 3), `slope [95% CI]` = ci(slope, slope_lo, slope_hi, d = 2),
              `intercept [95% CI]` = ci(recal_intercept, recal_intercept_lo, recal_intercept_hi, d = 3), ECE = fmt(ece),
              `fit (s)` = ifelse(is.na(fit_seconds), "–", formatC(fit_seconds, format = "f", digits = 0)))]
  out <- c(out, "## Results: every family", "",
           sprintf("All %d candidates are scored on the same %s Tune games. The table shows each family uncalibrated. v2's Platt, isotonic and spline variants are in `TABLES.md` (section 2) and are part of the BH family.",
                   nrow(cand), format(meta$n_tune_scored, big.mark = ",")), "",
           "- Slope and intercept come from the recalibration fit y ~ a + b·logit(p).",
           "- `fit (s)` sums the weekly fit times over the walk. v2 families' times are from their level-0 walk over 2014–2022 in this run; C1, C2 and E1 are not timed separately.", "",
           md_table(hh), "",
           "- **Significant differences:** nothing is significantly better than the close. Significantly worse (CI entirely below 0):",
           sprintf("  - new: %s;", paste(worse_new$candidate, collapse = ", ")),
           sprintf("  - v2: the unanchored base models %s (%d columns, including calibration variants).", paste(sort(unique(worse_v2$candidate)), collapse = ", "), nrow(worse_v2)),
           sprintf("- **Interval width tracks how far a family moves from the market:** S1 spans %.2f points, O1 %.2f, R1 %.2f, T1 %.2f, against %.2f for v2's XGB with isotonic calibration.",
                   width("S1"), width("O1"), width("R1"), width("T1"), {r <- sc[candidate == "XGB" & calibration == "isotonic"]; 100 * (r$skill_hi - r$skill_lo)}),
           "- **By season** (TABLES.md section 5): no family is ahead of the close in every season.",
           sprintf("  - S1's positive total comes from 2020 (%s) and 2021 (%s).", pcs(by_s("S1", 2020)), pcs(by_s("S1", 2021))),
           sprintf("  - It is behind in 2018 (%s), 2019 (%s) and 2022 (%s).", pcs(by_s("S1", 2018)), pcs(by_s("S1", 2019)), pcs(by_s("S1", 2022))), "")

  # probability quality
  rq <- rel[calibration == "none", .(bins_outside = sum(mean_p < obs_lo | mean_p > obs_hi), max_gap = max(abs(obs_rate - mean_p))), by = candidate]
  pq <- merge(unc[, .(candidate, ece, slope, slope_lo, slope_hi, recal_intercept, recal_intercept_lo, recal_intercept_hi, citl, citl_lo, citl_hi)],
              rq, by = "candidate")
  pq <- rbind(merge(c0[, .(candidate, ece, slope, slope_lo, slope_hi, recal_intercept, recal_intercept_lo, recal_intercept_hi, citl, citl_lo, citl_hi)], rq, by = "candidate"), pq)
  pq <- pq[order(match(candidate, h$candidate))]
  pqq <- pq[, .(candidate, ECE = fmt(ece), `slope b [95% CI]` = ci(slope, slope_lo, slope_hi, d = 2),
                `intercept a [95% CI]` = ci(recal_intercept, recal_intercept_lo, recal_intercept_hi, d = 3),
                `calibration-in-the-large [95% CI]` = ci(citl, citl_lo, citl_hi, d = 3),
                `bins outside Wilson CI (of 10)` = bins_outside, `largest bin gap` = fmt(max_gap, 3))]
  out <- c(out, "## Probability quality", "",
           "For each family, uncalibrated:",
           "- **Logistic recalibration:** y ~ a + b·logit(p). Perfect calibration is a = 0, b = 1; b < 1 means too extreme, b > 1 too timid.",
           "- **Calibration-in-the-large:** the intercept with the slope fixed at 1.",
           "- **ECE:** 10 equal-count bins.",
           "- **Reliability:** each bin's mean prediction against the observed home-win rate.",
           "  - `bins outside` counts bins whose observed rate's Wilson 95% CI excludes the mean prediction. About 0.5 such bins in 10 are expected by chance.",
           "  - The full 10-bin tables, with n per bin and the CIs, are in `TABLES.md` section 4 and `scores/reliability_tune.csv`, which also covers every v2 calibration variant.", "",
           md_table(pqq), "",
           sprintf("- **The close itself is calibrated on Tune:** slope %s, intercept %s.", ci(c0$slope, c0$slope_lo, c0$slope_hi, d = 2),
                   ci(c0$recal_intercept, c0$recal_intercept_lo, c0$recal_intercept_hi, d = 3)),
           "  - Its intercept leans negative: home teams won slightly less often than the close implied. The CI includes zero.",
           "  - That lean is what the walk-forward intercepts of S1 and T1 pick up.",
           sprintf("- **Miscalibrated uncalibrated families:** %s. Its intercept or slope CI misses the ideal value. It is an unanchored base model, not a candidate.",
                   if (nrow(miscal)) paste(sprintf("%s (slope %s, intercept %s)", miscal$candidate, fmt(miscal$slope, 2), fmt(miscal$recal_intercept, 3)), collapse = "; ") else "none"),
           "- **v2's isotonic maps** still produce slopes of about 0.87 (too extreme), as v2 found.", "")

  # controls
  cc <- ctl[, .(model, `refit as` = family_type,
                `skill vs climatology [95% CI]` = paste0(pct(skill_vs_climatology), " [", pct(skill_lo), ", ", pct(skill_hi), "]"),
                passed, `point <= 0` = point_not_positive)]
  out <- c(out, "## Controls", "",
           "- **Shuffled labels:**",
           "  - Outcomes are permuted globally with v2's seed: the same permutation as v2's control.",
           "  - Every learner is refit walk-forward on the permuted labels. That includes the four level-0 families feeding the meshes (GBM's first shuffled-label control), followed by every new family.",
           "  - Each is scored on Tune against an expanding home-win-rate climatology.",
           "  - **Pass rule (v2's):** the lower bound of the skill CI is not above 0. The table also shows whether the point estimate is ≤ 0.", "",
           md_table(cc), "",
           sprintf("- **Result:** %d of %d pass. %s", sum(ctl$passed), nrow(ctl),
                   if (nrow(ctl_pos)) sprintf("Point estimates above 0: %s, each with a CI that includes 0.", paste(sprintf("%s %s", ctl_pos$model, pcs(ctl_pos$skill_vs_climatology, 3)), collapse = ", ")) else "Every point estimate is at or below 0."),
           "- **Reproduction of v2's control:** LR_E1, GLMNET and XGB reproduce v2's committed control values, because they are the same refits on the same permutation.",
           "- **What the anchored families show:** they are far below climatology under permutation, because the close they are anchored to carries no information about permuted outcomes. That is the expected behaviour of an anchored model, not a defect.",
           sprintf("- **N1 and N1_NARROW are identical under permutation** (%s each). Identical predictions mean both CVs picked the same size and a decay of at most 100 (N1_NARROW's grid) on the permuted labels.",
                   pcs(ctl[model == "N1", skill_vs_climatology])),
           "- **Leakage, determinism and point in time** are covered by the tests above.",
           sprintf("- **Reproducibility:** a second full run of `sprint.R` reproduced %d of %d CSVs byte for byte (`determinism.csv`; `backtest/v3/check_rerun.R`).", sum(dt$identical), nrow(dt)),
           "- **v2 is unchanged:** the re-run reproduced all of v2's files byte for byte, and level 0 matches v2's committed Tune predictions.", "")

  # most useful mesh
  out <- c(out, "## Which mesh is most useful, and why", "",
           "**S1, the stacked mesh**, though not because it beats the close. Three reasons:",
           sprintf("- **Accuracy and stability.** It has the best point estimate of any candidate, %s, with one of the narrowest intervals (%.2f points wide, against %.2f for R1). That interval comes from moving only slightly from the market: mean |logit gap| %s.",
                   sk(row("S1")), width("S1"), width("R1"), fmt(row("S1")$mean_abs_logit_vs_close, 3)),
           sprintf("- **Cost.** About %.0f s of fitting on top of level 0, against %.0f s for R1.", fit_of("S1"), fit_of("R1")),
           "- **It is interpretable, and its fit is the main finding of this sprint.**",
           "  - The meta-learner shrinks every level-0 weight to zero in every Tune week. None of the seven models (logistic, glmnet, XGBoost, gbm, Elo, EPA, ensemble) carries information the close lacks.",
           sprintf("  - What S1 adds is a walk-forward intercept: on average %s in 2018, %s in 2020 and %s in 2021 (logit scale), tracking the close's own negative intercept on Tune.",
                   fmt(s1_int[season == 2018, int], 3), fmt(s1_int[season == 2020, int], 3), fmt(s1_int[season == 2021, int], 3)),
           "  - That component needs no level-0 model at all. It is a one-parameter correction of home-field advantage in the close.",
           "  - One possible explanation is the shift in home-field advantage around the 2020 season played without crowds. This run does not test it.",
           "",
           "**The other meshes:**",
           sprintf("- **O1 (online blend)** is the most stable runner-up: %s, with no tuning on Tune. It needs the full level-0 stack, though, and its weights end on the close and the anchored blends.", sk(row("O1"))),
           sprintf("- **R1 (XGBoost on the logistic residual)** gets a similar point estimate (%s) with an interval %.1f times as wide: boosting adds variance, not information, which repeats v2's finding.",
                   sk(row("R1")), width("R1") / width("S1")),
           sprintf("- **S1_MIN** (the less-shrunk lambda) scores %s. Letting the level-0 weights move away from zero lowers the point estimate; the difference from S1 is within noise.", sk(row("S1_MIN"))), "")

  out <- c(out, "## Verdict", "",
           "- **Nothing beats the closing moneyline on the Tune window,** whether a mesh of XGBoost and logistic regression or any of the other families tried (GAM, team mixed model, neural net, online blend).",
           "- **The more flexible the family, the closer its cross-validation pushes it to the market:**",
           "  - the stack zeroes its model weights;",
           sprintf("  - the booster's cross-validated rounds fall to %g by %d;", r1s$med[nrow(r1s)], r1s$season[nrow(r1s)]),
           "  - the GAM shrinks its smooths away;",
           "  - the mixed model finds almost no team variance;",
           "  - the net is decayed onto the close.",
           "- **Probabilities:** the anchored families are calibrated about as well as the close itself. None has a slope or intercept CI that excludes the ideal value.",
           "- **Overall:** this repeats v2's conclusion with more model capacity. At about 270 games a season, public pre-kickoff information adds nothing detectable beyond the closing price.",
           "- **Status:** it is exploration on a window already used, so it is evidence of absence at this sample size, not proof that no edge exists.", "")

  out <- c(out, "## What to pre-register in the v2 protocol (proposals only; `PROTOCOL-DRAFT.md` is unchanged)", "",
           "1. **No v3 family has earned a place as a likely winner.** On this evidence the draft's L1, G1 and X1 (and C3 when it is point in time) remain the right candidates.",
           "2. **Optional, if the owner wants one mesh in:** S1 in its reduced form, \"close plus a walk-forward intercept\".",
           sprintf("   - Why: one parameter, no Tune-selected inputs, and an interval %.2f points wide, against %.2f for X1 (v2's XGB).",
                   width("S1"), width("XGB")),
           "   - It should *replace* X1 rather than be added, so the multiplicity stays at four.",
           "   - The hypothesis it tests is narrow: does the close misprice home-field advantage on average?",
           "3. **Keep the v2 choices that v3 supports:**",
           "   - anchor every candidate on the market;",
           "   - use no calibration map for anchored blends (their recalibration slopes cover 1, and isotonic still over-steepens);",
           "   - run the shuffled-label control on every learner, now including gbm.",
           "4. **Do not pre-register G2** (its features were selected on Tune), **T1** (almost no team variance) or **N1** (its CV pins it to the close).", "")

  out <- c(out, "## Disclosures (choices made after seeing a Tune result)", "",
           "- **N1's decay grid.**",
           "  - The first development run used decay 1–100. Its CV chose the grid edge (100) in every season, and that run's Tune score had been seen.",
           "  - The grid was widened to 1–10,000 so the CV optimum could be interior. The CV then chose the new edge, 10,000, in every season, which is the limit where the net becomes the close.",
           sprintf("  - The first version is kept as **N1_NARROW** (%s) in every table and in the BH family, so the choice is visible.", sk(row("N1_NARROW"))),
           "- **O1's eta grid.**",
           "  - The first grid started at 0.5, and the selection on 2014–2017 chose that edge. It was widened to 2^-4…2^6, and 0.5 is the interior optimum, so O1's predictions did not change (`meshes/o1_eta_grid.csv`).",
           "  - eta = 0.5 is also the largest rate at which squared loss on [0, 1] is exp-concave, the condition for EWA's ln(N)/eta regret bound.",
           "- **G2's features** were chosen from v2's Tune screen (raw p < 0.10). Its Tune score is therefore optimistic, and G2_GAPS is the selection-free comparison.",
           "- **S1_MIN** was declared as a sensitivity variant in the code before any Tune result was seen.",
           "- **Development runs** used the same Tune window. Every number in this report comes from the committed run in this directory.", "")

  cm <- comp[stage %in% c("level0 (v2 code)", "v3 new")]
  out <- c(out, "## Compute", "",
           sprintf("- **Whole run:** %.0f s wall-clock with %d worker processes. That covers level 0 for 2014–2022, the 9 new candidates, and the full shuffled-label control including its level 0.", meta$runtime_sec, meta$workers),
           sprintf("- **Level 0 stage:** %.0f s.", meta$level0$wall_seconds),
           sprintf("- **New families' fits:** %.0f s of fitting in total. The most expensive are N1 (%.0f s, mostly its CV) and G2 (%.0f s).",
                   sum(cm[stage == "v3 new", fit_seconds]), fit_of("N1"), fit_of("G2")),
           "- Per-family numbers: `compute/seconds.csv` and `TABLES.md` section 9.", "")
  bt3_write_md(out, file.path(dir, "REPORT.md"))
}

if (sys.nframe() == 0L) {
  a <- commandArgs(trailingOnly = TRUE)
  if (!length(a)) stop("usage: Rscript backtest/v3/report.R <blend research dir>")
  cat("wrote", bt3_render_tables(a[1]), "\n")
  cat("wrote", bt3_render_report(a[1]), "\n")
}
